cask "iterm2"
cask "libreoffice"
cask "vlc"
cask "brave-browser"

# Python and build dependencies
brew "openssl"
brew "readline"
brew "sqlite3"
brew "xz"
brew "zlib"
brew "uv"

# General
brew "autojump"
brew "git"
brew "htop"
brew "jq"
brew "magic-wormhole"
brew "neovim"
brew "node"
cask "docker"
cask "maccy"

brew "rsync"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "tree"
brew "wget"
brew "yq"
brew "zplug"

# Terraform
tap "hashicorp/tap"
brew "hashicorp/tap/terraform"
brew "terraform-docs"
brew "tflint"
tap "tofuutils/tap"
brew "tofuenv"
brew "ansible"

# Personal
cask "calibre"
cask "transmission"
cask "lulu"
cask "midi-monitor"
cask "arduino-ide"
cask "creality-print"
